### ISSUE TITLE
Geolocation on HostGroup

### ISSUE THREAD

**Issue by aledr** [nbuchwitz/icingaweb2-module-map#30]
Hi!

Are you considering support geolocation coordinates to HostGroup?

Thanks.

**Comment by nbuchwitz** [comment]
Nothing in pipeline for now, but could consider to add a this as feature in one of the upcomming releases. It might be an interessting thing for big environments, where many hosts are located together. 

Due to changes in the representation layer (popups et al.) this would be a bigger milestone and take some time.

Nicolai

**Comment by dnsmichi** [comment]
AFAIK you cannot fetch those details from a hostgroup object using the Icinga Web 2 resources yet. There's no custom.ariable field for these objects inside the IDO database.

**Comment by aledr** [comment]
@dnsmichi and @nbuchwitz in this case do you have any hint about how to apply the geolocation variable without using a template or directly in the host?
In my case the template is used for all hosts, so It is not a good place for that.

**Comment by GrexAut** [comment]
I have 200 Hostsgroups with each ~25 Hosts on it. I added Geolocation variable with Icinga2 API
CURL Command:
`curl -k -s -u api_user:password -H 'Accept: application/json' -X POST 'https://IP:5665/v1/objects/hosts/HOSTNAME' -d '{"attrs":{"vars.geolocation":"LAT,LNG}}'`
